## Volatility Filtering for Optimal Timing for Train and Inference

In [1]:
import pandas as pd
import numpy as np

## Data Loader
## Input to this NB is the generated csv file from data_handler.py given Ticker

In [2]:
df = pd.read_csv("RL_Data.csv")
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['date'] = df['timestamp'].dt.date
df = df.sort_values('timestamp').reset_index(drop=True) # date sort
#df['log_return'] = np.log(df['close'] / df['close'].shift(1))  # percentage->amplify for GARCH fitting
df = df.dropna(subset=['log_return']).reset_index(drop=True)
df = df[['timestamp','date','ask_price_1', 'ask_size_1','bid_price_1','bid_size_1',
         'ask_price_2', 'ask_size_2','bid_price_2','bid_size_2',
         'ask_price_3', 'ask_size_3','bid_price_3','bid_size_3',
         'ask_price_4', 'ask_size_4','bid_price_4','bid_size_4',
         'ask_price_5', 'ask_size_5','bid_price_5','bid_size_5',
         'open','high','low','close',
         'volume','volatility','log_return']]

In [3]:
## Optimal Timing for training
df_sorted = df.sort_values(['date', 'volatility'])
df_filtered = df_sorted.groupby('date').head(80).reset_index(drop=True)
daily_volume = df_filtered.groupby('date')['volume'].sum().reset_index()
daily_volume.rename(columns={'volume': 'daily_volume'}, inplace=True)
df_filtered = df_filtered.merge(daily_volume, on='date', how='left')
df_filtered.head()

,timestamp,date,ask_price_1,ask_size_1,bid_price_1,bid_size_1,ask_price_2,ask_size_2,bid_price_2,bid_size_2,...,bid_price_5,bid_size_5,open,high,low,close,volume,volatility,log_return,daily_volume
0,2023-09-12 15:24:00+00:00,2023-09-12,176.43,20100,176.51,500,176.43,107600.0,176.51,40500.0,...,176.51,27600.0,176.47,176.51,176.43,176.43,13475.0,0.000865,-0.000283,1211098.0
1,2023-09-12 15:25:00+00:00,2023-09-12,176.36,20000,176.45,24800,176.36,10000.0,176.45,61100.0,...,176.45,61100.0,176.44,176.45,176.36,176.37,14430.0,0.000943,-0.000340,1211098.0
2,2023-09-12 15:26:00+00:00,2023-09-12,176.36,42500,176.42,3000,176.36,47500.0,176.42,10900.0,...,176.42,3000.0,176.37,176.42,176.35,176.37,12824.0,0.000943,0.000000,1211098.0
3,2023-09-12 15:27:00+00:00,2023-09-12,176.38,37500,176.47,31600,176.38,22500.0,176.47,10000.0,...,176.47,45200.0,176.39,176.47,176.37,176.46,9822.0,0.000998,0.000510,1211098.0
4,2023-09-12 15:20:00+00:00,2023-09-12,176.30,20000,176.37,10000,176.30,24000.0,176.37,12500.0,...,176.37,30000.0,176.30,176.37,176.30,176.35,17686.0,0.001039,0.000227,1211098.0

In [4]:
df_filtered = df_filtered[['timestamp','ask_price_1', 'ask_size_1','bid_price_1','bid_size_1',
         'ask_price_2', 'ask_size_2','bid_price_2','bid_size_2',
         'ask_price_3', 'ask_size_3','bid_price_3','bid_size_3',
         'ask_price_4', 'ask_size_4','bid_price_4','bid_size_4',
         'ask_price_5', 'ask_size_5','bid_price_5','bid_size_5',
         'open','high','low','close','daily_volume',
         'volume','volatility','log_return']]
df_filtered.to_csv("RL_Data_opt_timing.csv",index=False)

## This approach first decision-making on optimal timing
## Then throw the sizing part to RL agent for training.
## As for inference, we need to forecast ask1 price/size, bid1 price/ size, open, volume, daily volume, and volatility

In [5]:
steps_forward = 390 # one trading day forward
df.set_index('timestamp', inplace=True)
df['time'] = df.index.time
df['date'] = df.index.date
last_date = df['date'].max()
next_date = last_date + pd.Timedelta(days=1)
while next_date.weekday() >= 5:  # 5 = Saturday, 6 = Sunday
    next_date += pd.Timedelta(days=1)

start_time = pd.Timestamp(f"{next_date} 13:30:00")
end_time = pd.Timestamp(f"{next_date} 19:59:00")

df_forecast = pd.DataFrame({
    'timestamp': pd.date_range(start=start_time, periods=390, freq='1min'),
    'ask_price_1': np.zeros(steps_forward,dtype=float),
    'ask_size_1' : np.zeros(steps_forward,dtype=int),
    'bid_price_1' : np.zeros(steps_forward,dtype=float),
    'bid_size_1' : np.zeros(steps_forward,dtype=int),
    'open': np.zeros(steps_forward,dtype=float),
    'volume': np.zeros(steps_forward,dtype=int),
    'volatility': np.zeros(steps_forward,dtype=float),
    'daily_volume' : np.zeros(steps_forward,dtype=float),
})
df_forecast.set_index('timestamp', inplace=True)
df_forecast['time'] = df_forecast.index.time
df_forecast['date'] = df_forecast.index.date

In [6]:
from datetime import timedelta
def non_recurrent_hist_mean(train,test,col,window_size):
    train_dates = sorted(train['date'].unique())
    forecast=[]
    conf_lower=[]
    conf_upper=[]
    for idx, row in test.iterrows():
        time_to_forecast = row['time']
        date_to_forecast = row['date']
        past_dates = [date_to_forecast - timedelta(days=x) for x in range(1, window_size + 1)]
        past_dates = [d for d in past_dates if d.weekday() < 5 and d in train_dates] # exclude weekend
        past_data = train[(train['time'] == time_to_forecast) & (train['date'].isin(past_dates))][col]
        historical_mean = past_data.mean()
        if np.isnan(historical_mean):
            historical_mean = train['bid'].iloc[-1] # last close price
        forecast.append(historical_mean)
    forecast=np.array(forecast)
    return forecast

ask_price_1_forecast = non_recurrent_hist_mean(df, df_forecast, 'ask_price_1', 3)
ask_size_1_forecast = non_recurrent_hist_mean(df, df_forecast, 'ask_size_1', 3).astype(int)
import matplotlib.pyplot as plt

In [7]:
df_forecast['ask_price_1'] = ask_price_1_forecast
df_forecast['ask_size_1'] = ask_size_1_forecast
df_forecast['bid_price_1'] = non_recurrent_hist_mean(df, df_forecast, 'bid_price_1', 3)
df_forecast['bid_size_1'] = non_recurrent_hist_mean(df, df_forecast, 'bid_size_1', 3).astype(int)
df_forecast['open'] = non_recurrent_hist_mean(df, df_forecast, 'open', 3)
df_forecast['volume'] = non_recurrent_hist_mean(df, df_forecast, 'volume', 3).astype(int)
df_forecast['volatility'] = non_recurrent_hist_mean(df, df_forecast, 'volatility', 3)
df_forecast = df_forecast.reset_index()

## We pick 20 low volatility as optimal timing

In [8]:
optimal_timing=df_forecast.loc[df_forecast['volatility']<=np.percentile(df_forecast['volatility'].values, 5),:] # we keep 5% for optimal timing
optimal_timing

,timestamp,ask_price_1,ask_size_1,bid_price_1,bid_size_1,open,volume,volatility,daily_volume,time,date
99,2024-09-23 15:09:00,230.37,3000,230.48,26000,230.410,19163,0.001340,0.0,15:09:00,2024-09-23
100,2024-09-23 15:10:00,230.30,1000,230.42,20000,230.410,27847,0.001114,0.0,15:10:00,2024-09-23
167,2024-09-23 16:17:00,231.26,10000,231.36,10000,231.280,15045,0.001236,0.0,16:17:00,2024-09-23
174,2024-09-23 16:24:00,231.38,10000,231.48,34000,231.470,15810,0.001356,0.0,16:24:00,2024-09-23
175,2024-09-23 16:25:00,231.41,10000,231.53,17000,231.460,17959,0.001340,0.0,16:25:00,2024-09-23
176,2024-09-23 16:26:00,231.44,29000,231.61,14500,231.530,21271,0.001346,0.0,16:26:00,2024-09-23
181,2024-09-23 16:31:00,231.65,20000,231.74,5000,231.720,17331,0.001276,0.0,16:31:00,2024-09-23
182,2024-09-23 16:32:00,231.56,10000,231.70,15000,231.655,20030,0.001356,0.0,16:32:00,2024-09-23
183,2024-09-23 16:33:00,231.57,72400,231.63,12900,231.580,11889,0.001179,0.0,16:33:00,2024-09-23
184,2024-09-23 16:34:00,231.59,6700,231.66,10000,231.600,6917,0.000981,0.0,16:34:00,2024-09-23
185,2024-09-23 16:35:00,231.43,3000,231.64,10000,231.620,23476,0.001195,0.0,16:35:00,2024-09-23
186,2024-09-23 16:36:00,231.34,24800,231.48,5000,231.460,20465,0.001285,0.0,16:36:00,2024-09-23
343,2024-09-23 19:13:00,231.40,31700,231.57,20000,231.560,36016,0.001358,0.0,19:13:00,2024-09-23
344,2024-09-23 19:14:00,231.45,4400,231.60,7500,231.470,31193,0.001308,0.0,19:14:00,2024-09-23
345,2024-09-23 19:15:00,231.45,4400,231.56,2000,231.440,19999,0.001336,0.0,19:15:00,2024-09-23
346,2024-09-23 19:16:00,231.44,10000,231.54,20000,231.540,27063,0.001335,0.0,19:16:00,2024-09-23
347,2024-09-23 19:17:00,231.46,10000,231.56,10000,231.530,34302,0.001161,0.0,19:17:00,2024-09-23
348,2024-09-23 19:18:00,231.44,8500,231.54,8700,231.540,27720,0.001092,0.0,19:18:00,2024-09-23
349,2024-09-23 19:19:00,231.41,23700,231.51,4000,231.510,30356,0.001064,0.0,19:19:00,2024-09-23
354,2024-09-23 19:24:00,231.68,10000,231.85,2000,231.820,34080,0.001322,0.0,19:24:00,2024-09-23

In [14]:
optimal_timing=optimal_timing.copy()
optimal_timing['daily_volume'] = optimal_timing['volume'].sum()
optimal_timing = optimal_timing[['timestamp','ask_price_1', 'ask_size_1','bid_price_1','bid_size_1',
                                'open','volume','daily_volume','volatility']]
optimal_timing

,timestamp,ask_price_1,ask_size_1,bid_price_1,bid_size_1,open,volume,daily_volume,volatility
99,2024-09-23 15:09:00,230.37,3000,230.48,26000,230.410,19163,457932,0.001340
100,2024-09-23 15:10:00,230.30,1000,230.42,20000,230.410,27847,457932,0.001114
167,2024-09-23 16:17:00,231.26,10000,231.36,10000,231.280,15045,457932,0.001236
174,2024-09-23 16:24:00,231.38,10000,231.48,34000,231.470,15810,457932,0.001356
175,2024-09-23 16:25:00,231.41,10000,231.53,17000,231.460,17959,457932,0.001340
176,2024-09-23 16:26:00,231.44,29000,231.61,14500,231.530,21271,457932,0.001346
181,2024-09-23 16:31:00,231.65,20000,231.74,5000,231.720,17331,457932,0.001276
182,2024-09-23 16:32:00,231.56,10000,231.70,15000,231.655,20030,457932,0.001356
183,2024-09-23 16:33:00,231.57,72400,231.63,12900,231.580,11889,457932,0.001179
184,2024-09-23 16:34:00,231.59,6700,231.66,10000,231.600,6917,457932,0.000981
185,2024-09-23 16:35:00,231.43,3000,231.64,10000,231.620,23476,457932,0.001195
186,2024-09-23 16:36:00,231.34,24800,231.48,5000,231.460,20465,457932,0.001285
343,2024-09-23 19:13:00,231.40,31700,231.57,20000,231.560,36016,457932,0.001358
344,2024-09-23 19:14:00,231.45,4400,231.60,7500,231.470,31193,457932,0.001308
345,2024-09-23 19:15:00,231.45,4400,231.56,2000,231.440,19999,457932,0.001336
346,2024-09-23 19:16:00,231.44,10000,231.54,20000,231.540,27063,457932,0.001335
347,2024-09-23 19:17:00,231.46,10000,231.56,10000,231.530,34302,457932,0.001161
348,2024-09-23 19:18:00,231.44,8500,231.54,8700,231.540,27720,457932,0.001092
349,2024-09-23 19:19:00,231.41,23700,231.51,4000,231.510,30356,457932,0.001064
354,2024-09-23 19:24:00,231.68,10000,231.85,2000,231.820,34080,457932,0.001322

In [15]:
optimal_timing.to_csv("RL_Data_opt_timing_inference.csv",index=False)

<h1> RL Model for picking optimal bet size</h1>
<h2>Training</h2>
<h3>The input to this block is a CSV with optimal timings.</h3>

In [5]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt


from GordonRitter.utils.bet_sizing_model_utils import BetSizingModel
from GordonRitter.utils.bet_sizing_env import TradingEnvironment

#Data collection

data = pd.read_csv("RL_Data_opt_timing_inference.csv") 

state_columns = ['bid_price_1', 'bid_size_1', 'open', 'volume','daily_volume', 'volatility']

#OPTIMAL TIMINGS PER DAY
optm_pts_per_day = 20

# Unifying the type of numerical columns 
float_cols = data.select_dtypes(include=['float','int']).columns
data[float_cols] = data[float_cols].astype(np.float32)

#Handling missing values
rows_with_nan = data.isna().any(axis=1)
data.loc[rows_with_nan] = data.ffill().loc[rows_with_nan]
for col in data.columns:
    if data[col].isna().any():
        print(col)

#80% of the data is set aside for the training.
train_split = (int(data.shape[0]*0.8)//optm_pts_per_day)*optm_pts_per_day

data_train = data.iloc[:train_split]
data_test = data.iloc[train_split:]


# Min-Max normalization of float features.
data_min = data_train[float_cols].min()
data_max = data_train[float_cols].max()

for col in float_cols:
    data_train[col] = (data_train[col] - data_min[col])/(data_max[col]-data_min[col])
    data_test[col] = (data_test[col] - data_min[col])/(data_max[col]-data_min[col])


#Enviroment prep
env = TradingEnvironment(
    data=data_train,
    reset_count=optm_pts_per_day,
    initial_inventory=10000, # INVENTORY SIZE
    state_columns=state_columns
)

model = BetSizingModel(name='test1', env=env)

#Training the model
model.train(10000) #SAMPLES TO BE USED FOR TRAINING.

/tmp/ipykernel_54396/393306549.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = (data_train[col] - data_min[col])/(data_max[col]-data_min[col])
/tmp/ipykernel_54396/393306549.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = (data_test[col] - data_min[col])/(data_max[col]-data_min[col])
/home/malhar/Workspace/Blockhouse/Blockhouse-ML/blockhouse_ml/equities/sell/utils/data_handler.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data['mid_price'] = (self.data['high'] + self.data['low']) / 2
/home/malhar/Workspace/Blockhouse/Blockhouse-ML/blockhouse_ml/equities/sell/utils/data_handler.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data["mean_vol"] = self.data['mid_price'].pct_change().rolling(window=window_size).mean()
/home/malhar/Workspace/Blockhouse/Blockhouse-ML/blockhouse_ml/equities/sell/utils/data_handler.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data["mean_liq"] = self.data['volume'].rolling(window=window_size).mean()
/home/malhar/Workspace/Blockhouse/Blockhouse-ML/blockhouse_ml/equities/sell/utils/data_handler.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data['transaction_cost'] = self.data.apply(almgren, axis=1)
/home/malhar/Workspace/Blockhouse/Blockhouse-ML/GordonRitter/utils/bet_sizing_env.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data.ffill(inplace=True)

Training from scratch...

<h2>Model Inference</h2>

In [6]:
env = TradingEnvironment(
    data=data_test,
    reset_count=optm_pts_per_day,
    initial_inventory=10000,
    state_columns=state_columns
)

model.test(env=env, steps=int(data_test.shape[0]*0.95))
for action_list in env.tradelist:
# Each row tells how much of the total inventory
# to sell for the corresponding optimal of a day.

# THE RATIO SHOULD BE USED WITH CAPPING, LIMITING TOTAL
# TRADED VOLUME TO THE INVENTORY.  
    print(action_list)

/home/malhar/Workspace/Blockhouse/Blockhouse-ML/blockhouse_ml/equities/sell/utils/data_handler.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data['mid_price'] = (self.data['high'] + self.data['low']) / 2
/home/malhar/Workspace/Blockhouse/Blockhouse-ML/blockhouse_ml/equities/sell/utils/data_handler.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data["mean_vol"] = self.data['mid_price'].pct_change().rolling(window=window_size).mean()
/home/malhar/Workspace/Blockhouse/Blockhouse-ML/blockhouse_ml/equities/sell/utils/data_handler.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data["mean_liq"] = self.data['volume'].rolling(window=window_size).mean()
/home/malhar/Workspace/Blockhouse/Blockhouse-ML/blockhouse_ml/equities/sell/utils/data_handler.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data['transaction_cost'] = self.data.apply(almgren, axis=1)
/home/malhar/Workspace/Blockhouse/Blockhouse-ML/GordonRitter/utils/bet_sizing_env.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data.ffill(inplace=True)

[0.0, 0.5359386801719666, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0915442705154419, 0.0, 0.9156397581100464]
[0.0, 0.0, 0.0, 0.7577047944068909, 0.0, 0.0, 0.0, 0.0, 0.0, 0.009934604167938232, 0.0, 0.2774854302406311]
[0.756639301776886, 0.0, 0.2390347719192505, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04432767629623413]
[0.0, 0.0, 0.0, 0.02229940891265869, 0.0, 0.3253552317619324, 0.0, 0.08456993103027344, 0.0, 0.9807868599891663]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.7769777774810791, 0.0, 0.0, 1.0]
[0.0, 0.00875246524810791, 0.0, 0.0, 0.0, 0.5577006340026855, 0.0, 0.40579187870025635, 0.0, 0.0, 0.0, 0.0, 0.20845454931259155]
[0.0, 0.0, 0.014348328113555908, 0.0, 0.0, 0.0, 0.7988471984863281, 0.0, 0.0, 0.0, 0.3839157223701477]
[0.05111473798751831, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8005333542823792]
[0.0, 0.03880131244659424, 0.0, 0.18796586990356445, 0.0, 0.7995172142982483]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3543824553489685, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.39407992362976074]
[0.0, 0.0, 0.018535315990447998, 0.0, 0.0, 0.0, 0.0, 0.22856521606445312, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.23509913682937622, 0.0, 0.0, 0.0, 0.0, 0.0, 0.21038877964019775, 0.0, 0.0, 0.0, 0.0, 0.0, 0.09723454713821411, 0.0, 0.0, 0.06514734029769897]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4647178053855896]
[0.0, 0.0, 0.0, 0.0, 0.009704530239105225, 0.0, 0.0, 0.6241872310638428, 0.0, 0.510980486869812]
[0.0, 0.0, 0.560819149017334, 0.003217458724975586, 0.0, 0.0, 0.0, 0.0, 0.0, 0.007253110408782959, 0.0, 0.0, 0.0, 0.0, 0.27430176734924316, 0.0, 0.07298994064331055, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.9592674970626831, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0528411865234375]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6781392097473145, 0.0, 0.0, 0.0, 0.19082427024841309, 0.0, 0.003465116024017334, 0.6207745671272278]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.11409962177276611, 0.0, 0.2070733904838562, 0.0, 0.16694629192352295, 0.0, 0.0, 0.0, 0.0, 0.206365168094635, 0.0]
[0.5403343439102173, 0.0, 0.0, 0.41629791259765625, 0.0, 0.28279757499694824]
[0.07160729169845581, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4990392327308655, 0.0, 0.0, 0.0, 0.167979896068573, 0.103579580783844, 0.0, 0.0, 0.6140828132629395]
[0.0, 0.0, 0.0, 0.21299058198928833, 1.0]
[0.0, 0.0, 0.19499528408050537, 0.0, 0.5141183137893677, 1.0]
[0.0, 0.7669451236724854, 0.19908452033996582, 0.0, 0.22827446460723877]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.09854143857955933, 0.4092196822166443, 0.4013350009918213, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.12551140785217285, 0.0, 0.0, 0.0, 0.0, 0.0, 0.39647364616394043, 0.0, 0.5483070611953735]
[0.0, 0.0, 0.34414368867874146, 0.0, 0.0, 0.0, 0.0, 0.14720100164413452, 0.2188466191291809, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8653159141540527]
[0.10601186752319336, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0339512825012207, 0.2221558690071106, 0.0, 1.0]
[0.15103179216384888, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.06010192632675171, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4332026243209839, 0.0, 0.0, 0.047647178173065186, 0.0, 0.0, 0.19910335540771484, 0.14768821001052856]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3741825222969055, 0.0, 0.0, 0.34292733669281006, 0.0, 0.0]
[0.04136890172958374, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6095479130744934, 0.0, 0.0, 0.0, 0.08396613597869873, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3203849792480469]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.24809187650680542, 0.049590885639190674, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4188268780708313, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.14568477869033813, 0.22995150089263916, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1380389928817749, 0.19473493099212646, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.6621053814888, 0.4716641902923584]
[0.0, 0.0, 0.0, 0.07635170221328735, 0.0, 0.0, 0.0, 0.008439242839813232, 0.0, 0.0, 0.6856287121772766, 0.0, 0.5743675231933594]
[0.8455760478973389, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5054634213447571, 0.0, 0.0, 0.5392323136329651]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7099873423576355, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05650293827056885, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.23899227380752563, 0.36958158016204834, 0.35342133045196533, 0.0, 0.0, 0.0, 0.11107200384140015]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.45179086923599243, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2888616919517517, 0.39672380685806274]
[0.17920619249343872, 0.0, 0.38016223907470703, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.35570192337036133, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.022942185401916504, 0.0, 0.0, 0.0, 0.0718541145324707, 0.0, 0.7246866226196289, 0.0, 0.04217660427093506, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.6390925645828247, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5140320658683777, 0.1239173412322998, 0.0, 0.0, 0.19164109230041504, 0.674065113067627]
[0.0, 0.0, 0.17943018674850464, 0.23677480220794678, 0.0, 0.0, 0.308357834815979, 0.0, 0.010983288288116455, 0.0, 0.0, 0.3588895797729492]
[0.0, 0.0, 0.3478901982307434, 0.0, 0.0, 0.0, 0.0, 0.2398357391357422, 1.0]
[0.0, 0.0, 0.026410996913909912, 0.41355258226394653, 0.0, 0.0, 0.5102023482322693, 0.0, 0.48363548517227173]
[0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.6572939157485962, 0.0, 0.4034773111343384]
[0.0, 0.0, 0.596550464630127, 0.0, 0.0, 0.0, 0.9134323596954346]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6188422441482544, 0.20788884162902832, 0.0, 0.0, 0.0, 0.0, 0.7405131459236145]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1838524341583252, 0.0, 0.3406922221183777, 0.07673400640487671, 0.0, 0.0, 0.0, 0.0, 0.0, 0.19108164310455322, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7304846048355103, 0.6738086938858032]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.36074256896972656, 0.0, 0.20663559436798096, 0.0, 0.0, 0.0, 0.0, 0.24006378650665283, 0.0, 0.0, 0.4432089924812317]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.006356537342071533, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.12229025363922119, 0.4103773832321167, 0.0, 0.0, 0.12226986885070801, 0.0, 0.3493638038635254]
[0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.032244980335235596, 0.0, 0.04196822643280029, 0.0, 0.0, 0.6249934434890747, 0.0, 0.2290143370628357]
[0.41349321603775024, 0.09823095798492432, 0.0, 0.41065531969070435, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5889418721199036]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6759169697761536, 0.0, 0.0, 0.0, 0.0, 0.3265460729598999]
[0.0, 0.0, 0.21850401163101196, 0.0, 0.27854639291763306, 0.0, 0.0, 0.0, 0.0, 0.37697750329971313, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.39335066080093384]
[0.49472200870513916, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.38170677423477173, 0.0, 0.0]
[0.0, 0.0, 0.7883138060569763, 0.0, 0.4912174344062805]
[0.6583065986633301, 0.0, 0.0, 0.0709693431854248, 0.0, 0.0, 0.0, 0.19031047821044922, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.4638497829437256, 0.0, 0.09101134538650513, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.45828109979629517]
[0.0, 0.0, 0.0, 0.07232159376144409, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5385349988937378, 0.0, 0.0, 0.0, 0.03837168216705322, 0.0, 0.0]
[0.11787945032119751, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1975405216217041, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.5041249990463257, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.011117696762084961, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.029188871383666992, 0.0, 0.3216078281402588, 0.8076419234275818]
[0.0, 0.0, 0.0, 0.0, 0.39760953187942505, 0.005355656147003174, 0.922816276550293]
[0.0, 0.0, 0.46073752641677856, 0.0, 0.21776938438415527, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5652511119842529]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.4170844554901123, 0.6070651412010193]
[0.2929713726043701, 0.0, 0.9369364976882935]
[0.047261595726013184, 0.0, 0.05185180902481079, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3995528817176819, 0.0, 0.001808762550354004, 0.0, 0.8675993084907532]
[0.0, 0.0, 0.4956638813018799, 0.0, 0.0, 0.0, 0.0, 0.5998795628547668]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.14877313375473022, 0.0, 0.0, 0.41044414043426514, 0.0, 0.1568325161933899, 0.0, 0.0, 0.33671337366104126]
[1.0]
[0.0, 0.0, 0.1652732491493225, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 1.0]
[0.0, 0.6288832426071167, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.36525994539260864, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.03967452049255371, 0.0, 0.0, 0.0, 0.46047741174697876, 0.5277902483940125]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03852236270904541, 0.0, 0.6295837759971619, 0.0, 0.8039904832839966]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6017810702323914, 0.0, 0.0, 0.0, 0.0, 0.9404788613319397]
[0.0, 0.0, 0.5248969197273254, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.37785279750823975, 0.0, 0.004198610782623291, 0.0, 0.0, 0.0, 0.0, 0.5003426671028137, 0.0, 0.0, 0.0915495753288269, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7164727449417114]
[0.0, 0.0, 0.0, 0.0, 0.3237854838371277, 0.0, 0.36013174057006836, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.40130555629730225]
[0.08899915218353271, 0.0, 0.0, 0.10176455974578857, 0.0, 0.0, 0.0, 0.009947001934051514, 0.0, 0.0, 0.16880154609680176, 0.0, 0.0, 0.0, 0.8656221032142639]
[0.0, 0.0, 0.31531375646591187, 0.13589274883270264, 0.0, 0.0, 0.0, 0.0, 0.0, 0.37090152502059937, 0.0, 0.42517322301864624]
[0.0, 0.0, 0.40531831979751587, 0.0, 0.22626668214797974, 0.0, 0.087338387966156, 0.0, 0.0, 0.0, 0.1906719207763672, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.5698386430740356, 0.0, 0.0, 0.0, 0.0, 0.27077174186706543, 0.0, 0.0, 0.4683988690376282]
[1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8574718236923218, 0.0, 0.0, 0.19667577743530273]
[0.0, 0.10226136445999146, 0.0, 0.0, 0.2055085301399231, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3263036012649536, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7412234544754028]
[0.0, 0.0, 0.0, 0.0, 0.4626704454421997, 0.19279450178146362, 0.4123746156692505]
[0.24215221405029297, 0.0, 0.0, 0.2391033172607422, 0.953464150428772]
[0.0, 0.2400621771812439, 0.0, 0.0, 0.0, 0.20281362533569336, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5194002389907837, 1.0]
[0.0, 0.031035006046295166, 0.0, 0.0, 0.0, 0.2821529507637024, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6843553781509399, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06706792116165161]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.009919345378875732, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.26086699962615967, 0.0, 0.0, 0.0, 0.0, 0.27715474367141724, 0.6216035485267639]
[0.0, 0.0, 0.0, 0.17624902725219727, 0.3554561138153076, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.12821024656295776, 0.0, 0.0, 0.0, 0.22856438159942627, 0.0, 0.0, 0.0, 0.6349862217903137, 0.0, 0.0, 0.0, 0.003364384174346924, 0.030264854431152344]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.5960389375686646, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4063047766685486]
[0.0, 0.2509182095527649, 0.0, 0.0, 0.0, 0.30345940589904785, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.29367053508758545, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.38302499055862427, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.29134833812713623, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4735865592956543, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.20354151725769043, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4183485507965088, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.146886944770813, 0.0, 0.6441650986671448, 0.0, 0.0, 0.0, 0.07247066497802734, 0.0, 0.0, 0.0, 0.0, 0.30049997568130493]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.361336886882782, 0.0]
[0.0, 0.0, 0.1834140419960022, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.18599212169647217, 0.0, 0.0, 0.0, 0.0, 0.02502727508544922, 0.0, 0.09834843873977661]
[0.0, 0.0, 0.0, 1.0]
[0.10858583450317383, 0.0, 0.2076895833015442, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.054885268211364746, 0.0, 0.0, 1.0]
[0.7347800135612488, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.18976932764053345, 0.0, 0.3411603569984436]
[0.0, 0.06036102771759033, 0.03568059206008911, 0.0, 0.5056095719337463, 0.6695367693901062]
[0.0, 0.0, 0.0, 0.28630536794662476, 0.0, 0.0, 0.0, 0.0, 0.0, 0.403689980506897, 0.0, 0.0, 0.0, 0.0, 0.172429621219635, 0.0, 0.0, 0.0, 0.1795758605003357]
[0.0, 0.0, 0.31094980239868164, 0.0, 0.0, 0.04118549823760986, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1743626594543457, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.21009421348571777, 0.0, 0.024265289306640625, 0.0, 0.0, 0.0, 0.14637809991836548, 0.0, 0.0, 0.5773272514343262, 0.0, 0.0, 0.0, 0.09015733003616333]
[0.0, 0.0, 0.0, 0.29514259099960327, 0.0, 0.0, 0.0, 0.2981671094894409, 0.0, 0.0, 0.0, 0.0, 0.0, 0.537178099155426]
[0.0, 1.0]
[0.0, 0.7176486849784851, 0.0, 0.21762210130691528, 0.9839890003204346]
[1.0]
[0.0, 0.0, 0.0, 0.0, 0.31975609064102173, 0.0, 0.0, 0.0, 0.0, 0.29376310110092163, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08331036567687988, 0.0, 0.0]
[0.0, 0.0, 0.5013169646263123, 0.0, 0.6538864374160767]
[0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.26252979040145874, 0.505392849445343, 0.5090710520744324]
[0.0, 0.0, 0.0, 0.0, 0.10204946994781494, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8564920425415039, 0.0, 0.06806200742721558]
[0.0, 0.0, 0.0, 0.0, 0.08194661140441895, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03414565324783325, 0.0, 0.26646631956100464, 1.0]
[0.0, 0.0, 0.018997788429260254, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.005568861961364746, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.2574688792228699, 0.0, 0.0, 0.6996535062789917, 0.4429513216018677]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.46032440662384033, 0.0, 0.0, 0.0, 0.0, 0.9185340404510498]
[0.0, 0.2451028823852539, 0.09518188238143921, 0.028256893157958984, 0.0, 0.0, 0.0, 0.015080630779266357, 0.45367586612701416, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5176519751548767]
[0.0, 0.0, 0.0, 0.0, 0.6414178609848022, 0.0, 0.16879123449325562, 0.0, 0.0, 0.4643111824989319]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2367337942123413, 0.0, 0.0, 0.0, 0.0541568398475647, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04408138990402222, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.07111728191375732, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.18344050645828247, 0.0, 0.0, 0.0, 0.08891892433166504, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4509546160697937, 0.0909910798072815, 0.3904123902320862]
[0.03931725025177002, 0.0, 1.0]
[0.3688252568244934, 0.0, 0.0, 0.0, 0.17755001783370972, 0.7940888404846191]
[0.0, 0.0, 0.06805920600891113, 0.0, 0.37679892778396606, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02794671058654785, 0.0, 0.0, 0.02520465850830078, 0.014624416828155518, 0.0, 0.0, 0.0, 0.11254686117172241]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.6321817636489868, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.44257503747940063]
[0.0, 0.150945782661438, 0.0, 0.0, 0.6044301986694336, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2726038098335266]
[0.0, 0.0, 0.06144118309020996, 0.0, 0.0, 0.0, 0.45978397130966187, 0.0, 0.241796612739563, 0.0, 0.07938599586486816, 0.1429833173751831, 0.42296791076660156]
[0.0, 0.0, 0.6925836205482483, 0.0, 0.0, 0.0, 0.04136723279953003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06945013999938965, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0061893463134765625, 0.0, 0.0, 0.0, 0.0, 0.0, 0.71208655834198, 0.0, 0.0, 0.5231351852416992]
[0.14714771509170532, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.24695563316345215, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05113869905471802, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7499339580535889]
[0.0, 0.0, 0.0, 0.0, 0.09580689668655396, 0.7701244354248047, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1298898458480835, 0.2036229372024536]
[0.0, 0.0, 0.3728497624397278, 0.04541414976119995, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.11951947212219238, 0.06437373161315918, 0.0, 0.0, 0.0, 0.04454249143600464, 0.0, 0.012642860412597656, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.24991345405578613]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7575300931930542, 0.7584953308105469]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.486763060092926, 0.0, 0.805587887763977]
[0.0, 0.0, 0.5273391604423523, 0.0, 0.0, 0.320411741733551, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1405566930770874, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1656314730644226, 0.0, 0.0, 0.9517779350280762]
[0.0, 0.17416775226593018, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.25001949071884155, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.20064103603363037]
[0.0, 0.0, 0.0, 0.03424656391143799, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6382807493209839, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4675123691558838, 0.0, 0.6614190936088562]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7414560914039612, 0.0, 0.0, 0.0, 0.0, 0.0, 0.19750690460205078, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.09369444847106934, 0.0, 0.0, 0.39661622047424316, 0.0, 0.0, 0.0, 0.0, 0.0, 0.14235103130340576, 0.0, 0.0, 0.0, 0.0, 0.3429446816444397, 0.0]
[0.0, 0.45311814546585083, 0.5566787123680115]
[0.0, 1.0]
[0.6797729134559631, 0.0, 0.10812020301818848, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1293114423751831, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7544165253639221]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8488627076148987, 1.0]
[0.0, 0.0, 0.0, 0.052153825759887695, 0.0, 0.3242594003677368, 0.0, 0.0, 0.0, 0.44786345958709717, 0.0, 0.0, 0.0, 0.0, 0.641006588935852]
[0.0, 0.5245237350463867, 0.0, 0.0, 0.7487888336181641]
[0.0, 0.018072307109832764, 0.0, 0.2716449499130249, 0.0, 0.3292657136917114, 0.0, 0.0, 0.0, 0.0, 0.5031536817550659]
[0.0, 0.0, 0.12109231948852539, 0.27524369955062866, 0.0, 0.0, 0.22964990139007568, 0.0, 0.23481184244155884, 0.0, 0.08605802059173584, 0.0, 0.12603425979614258]
[0.4865942597389221, 0.0, 0.4874628186225891, 0.0, 0.0, 0.17361795902252197]
[0.019681572914123535, 0.060931265354156494, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.49933743476867676, 0.09412825107574463, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 1.0]
[0.0, 0.45651501417160034, 0.0, 0.0, 0.0, 0.5165614485740662, 0.0, 1.0]
[0.12282383441925049, 0.0, 0.8577066659927368, 0.0, 0.0, 0.005455374717712402, 0.22323918342590332]
[0.0, 0.0, 0.08135944604873657, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.010784626007080078, 0.0, 0.0, 0.0, 0.0, 0.20671534538269043, 0.0, 0.0, 0.0, 0.0]
[0.20412838459014893, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4830778241157532, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.16502463817596436, 0.0, 0.02530139684677124, 0.0, 0.013550937175750732, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.6027127504348755, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0004488229751586914, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.22758817672729492, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2503063678741455, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06743907928466797, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.219637930393219, 0.0, 0.0, 0.0, 0.8534197211265564]
[0.8681765198707581, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5678631663322449]