In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [44]:
df = pd.read_csv("./merged_bid_ask_ohlcv_data.csv")
df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values('timestamp').reset_index(drop=True)

In [45]:
# Effective Bid Ask Spread
def EffectiveBidAskSpread(data, window_size=60):
    ''' Spread is to measure liquidity, larger spread, less liquidity
    '''
    result = data[['timestamp','close']].copy()
    result['Delta_P_t'] = result['close'].diff()
    result['Delta_P_shift'] = result['Delta_P_t'].shift()
    
    result['EffectiveBidAskSpread'] = (
        result['Delta_P_t'].
                   rolling(window=window_size).cov(result['Delta_P_shift']).
                   apply(lambda x: max(0,(-x))**0.5)
    )
    data['EffectiveSpread'] = result['EffectiveBidAskSpread']
    
    return data
df = EffectiveBidAskSpread(df) # add Effective Spread

In [46]:
# High Low Volatility
def HLVolatility1(data, window_size=60):
    result = pd.DataFrame()
    result['timestamp'] = data['timestamp']
    
    result['HL_Volatility'] = (np.log(data['high'])-np.log(data['low']))**2
    result['HL_Volatility'] = result['HL_Volatility'].rolling(window=window_size).mean()
    result['HL_Volatility'] = (result['HL_Volatility']/(4*np.log(2)))**0.5
    df['HLVolatility'] = result['HL_Volatility']
    
    return df
df = HLVolatility1(df)

In [47]:
# Corwin-Schultz Spread
def CSSpread(data, window_size=60):
    result = pd.DataFrame()
    result['timestamp'] = data['timestamp']
    result['gama'] = (np.log(np.maximum(data['high'], data['high'].shift(1))/np.minimum(data['high'], data['high'].shift(1))))**2
    
    result['beta'] = (np.log(data['high']/data['low']))**2
    result['beta'] = (result['beta']+result['beta'].shift(1)).rolling(window=window_size).mean()
    
    result['alpha'] = result['beta']**0.5 * (2**0.5-1) / (3-2*2**0.5) - (result['gama'] / (3-2*2**0.5))**0.5
    result['alpha'] = result['alpha'].apply(lambda x:max(x,0)) # avoid negative spread
    
    result['S'] = 2*(np.exp(result['alpha'])-1)/(np.exp(result['alpha'])+1)
    df['CS_Spread'] = result['S']
    
    return df
df = CSSpread(df)

In [48]:
import statsmodels.api as sm
# Kyle's Lambda -> 1/lambda implies liquidity
def Kyle_Lambda(data):
    df = pd.DataFrame()
    df['date'] = data['timestamp'].dt.date
    df['delta_p_t'] = data['close'] - data['close'].shift(1)
    df['delta_price'] = data['close'] - data['close'].shift(1)
    df['b_t'] = np.sign(df['delta_price'])
    df['b_t'] = df['b_t'].replace(0, method='ffill')
    df['b_t'] = df['b_t'].fillna(1)
    df['signed_volume'] = df['b_t'] * data['volume']
    kyle_lambda_list = []
    grouped = df.dropna(subset=['delta_p_t', 'signed_volume']).groupby('date')
    for _, group in grouped:
        if len(group) > 1:
            X, y = group['signed_volume'], group['delta_p_t']
            X = sm.add_constant(X)
            model = sm.OLS(y, X)
            results = model.fit()
            lambda_hat = results.params['signed_volume']
            df.loc[group.index, 'Kyle_Lambda'] = lambda_hat
        else:
            df.loc[group.index, 'Kyle_Lambda'] = np.nan
    data['Kyle_Lambda'] = df['Kyle_Lambda']
    return data
df = Kyle_Lambda(df)

/var/folders/n4/y00km0293ls6k971pcx61wnr0000gn/T/ipykernel_51944/2997099337.py:9: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  df['b_t'] = df['b_t'].replace(0, method='ffill')

In [49]:
# Volume-Synchronized Probability of Informed Trading (VPIN) -> lead volatility
def VolumePIN(data, window_size=60):
    df = pd.DataFrame()
    df['Total_Bid_Size'] = data[['bid_size_1', 'bid_size_2', 'bid_size_3', 'bid_size_4', 'bid_size_5']].sum(axis=1)
    df['Total_Ask_Size'] = data[['ask_size_1', 'ask_size_2', 'ask_size_3', 'ask_size_4', 'ask_size_5']].sum(axis=1)
    df['OBI'] = (df['Total_Bid_Size'] - df['Total_Ask_Size']) / (df['Total_Bid_Size'] + df['Total_Ask_Size'])
    df['OBI'] = df['OBI'].replace([np.inf, -np.inf], np.nan).fillna(0)
    df['V_B'] = data['volume'] * (1 + df['OBI']) / 2 # estimate V^B
    df['V_S'] = data['volume'] * (1 - df['OBI']) / 2 # estimate V^S
    df['sum_V_B'] = df['V_B'].rolling(window=window_size).sum()
    df['sum_V_S'] = df['V_S'].rolling(window=window_size).sum()
    df['V'] = data['volume'].rolling(window=window_size).mean()
    df['numerator'] = (df['V_B'] - df['V_S']).abs().rolling(window=window_size).sum()
    df['denominator'] = window_size * df['V']
    df['denominator'] = df['denominator'].replace(0, np.nan)
    data['Volume_PIN'] = df['numerator'] / df['denominator']
    return data
df = VolumePIN(df)

In [50]:
# Fibonacci Retracement (maybe not so useful) -> support and resistance
def Fibo_Retrace(data, window_size=390):
    period_high = data['high'].rolling(window=window_size, min_periods=1).max()
    period_low = data['low'].rolling(window=window_size, min_periods=1).min()
    for i,level in enumerate([0.236, 0.382, 0.5, 0.618, 0.786]):
        data[f'Fib_Level_{i}'] = period_high - (period_high - period_low) * level
    return data
df = Fibo_Retrace(df)

In [51]:
df.iloc[100:110,-10:]

,EffectiveSpread,HLVolatility,CS_Spread,Kyle_Lambda,Volume_PIN,Fib_Level_0,Fib_Level_1,Fib_Level_2,Fib_Level_3,Fib_Level_4
100,0.0,0.000645,0.001901,0.000001,0.286293,178.74356,178.26322,177.875,177.48678,176.93406
101,0.0,0.000645,0.002708,0.000001,0.286614,178.74356,178.26322,177.875,177.48678,176.93406
102,0.0,0.000644,0.003664,0.000001,0.276853,178.74356,178.26322,177.875,177.48678,176.93406
103,0.0,0.000645,0.003392,0.000001,0.278046,178.74356,178.26322,177.875,177.48678,176.93406
104,0.0,0.000643,0.003663,0.000001,0.283555,178.74356,178.26322,177.875,177.48678,176.93406
105,0.0,0.000641,0.003651,0.000001,0.283426,178.74356,178.26322,177.875,177.48678,176.93406
106,0.0,0.000639,0.002406,0.000001,0.284223,178.74356,178.26322,177.875,177.48678,176.93406
107,0.0,0.000638,0.003355,0.000001,0.283809,178.74356,178.26322,177.875,177.48678,176.93406
108,0.0,0.000636,0.003072,0.000001,0.281541,178.74356,178.26322,177.875,177.48678,176.93406
109,0.0,0.000635,0.003612,0.000001,0.281605,178.74356,178.26322,177.875,177.48678,176.93406

In [55]:
# PCA
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [57]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df.drop(columns=['timestamp','symbol']).dropna())
pca = PCA(n_components=0.95, whiten=True)
df_pca = pca.fit_transform(df_scaled)

In [61]:
df_pca = pd.DataFrame(df_pca, columns=[f'PC{i+1}' for i in range(df_pca.shape[1])])

### Reduce the sample space from 40 to 11.

In [62]:
df_pca.head()

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11
0,-0.721715,-0.841195,-0.438455,0.349423,-0.879362,-0.859075,-0.924684,0.512443,-0.743122,-0.382969,0.091198
1,-0.754844,-0.352074,-0.132352,0.808529,-0.428902,0.618425,-0.602751,0.139250,-1.235214,-0.583261,2.011003
2,-0.737532,-0.623757,0.159126,0.696161,-0.017794,1.020565,-0.568360,0.185737,-1.265953,-0.627798,1.220056
3,-0.752353,-0.431801,-0.035609,0.105487,1.411377,2.816725,-0.726755,0.338953,-1.020472,-0.415737,-0.559806
4,-0.738441,-0.459832,0.184880,0.786086,-1.052397,-0.712263,-0.900904,0.316035,-0.984569,-0.503548,1.033149

In [60]:
df.drop(columns=['timestamp','symbol']).head()

,bid_price_1,bid_price_2,bid_price_3,bid_price_4,bid_price_5,bid_size_1,bid_size_2,bid_size_3,bid_size_4,bid_size_5,...,EffectiveSpread,HLVolatility,CS_Spread,Kyle_Lambda,Volume_PIN,Fib_Level_0,Fib_Level_1,Fib_Level_2,Fib_Level_3,Fib_Level_4
0,179.66,179.66,179.66,179.66,179.66,27600.0,30000.0,23100.0,23100.0,43100.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,179.89,179.89,179.89,179.89,179.89,21200.0,900.0,1200.0,20300.0,300.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,180.12,180.12,180.12,180.12,180.11,10000.0,30000.0,20000.0,30000.0,10000.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,179.99,179.99,179.99,179.99,179.99,17400.0,19700.0,9700.0,19700.0,9700.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,179.78,179.78,179.78,179.78,179.78,10000.0,10000.0,12100.0,10600.0,10600.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
feature_contributions = pca.components_
feature_contributions

array([[ 2.24000291e-01,  2.24000226e-01,  2.24000092e-01,
         2.23999990e-01,  2.23999881e-01, -4.07980593e-02,
        -4.26397390e-02, -4.08607162e-02, -4.09221769e-02,
        -4.04867285e-02,  2.23952846e-01,  2.23952924e-01,
         2.23953071e-01,  2.23953182e-01,  2.23953304e-01,
        -3.82808177e-02, -4.13500091e-02, -4.12060719e-02,
        -3.97872544e-02, -3.98305082e-02,  0.00000000e+00,
         0.00000000e+00,  8.06188514e-02,  2.23977738e-01,
         2.24000764e-01,  2.23952233e-01,  2.23975334e-01,
         3.54598915e-03, -6.46478452e-04,  4.75552601e-02,
         3.47905002e-02,  5.65662707e-02,  4.80928962e-02,
         1.09542779e-01,  6.00603901e-02,  2.23894647e-01,
         2.23822781e-01,  2.23709253e-01,  2.23544651e-01,
         2.23219565e-01],
       [ 3.42872408e-02,  3.42888549e-02,  3.42918893e-02,
         3.42942921e-02,  3.42970311e-02,  2.20274317e-01,
         2.40981069e-01,  2.58419811e-01,  2.58983042e-01,
         2.52017358e-01,  3.49956717e-02,  3.49936345e-02,
         3.49900155e-02,  3.49874209e-02,  3.49843148e-02,
         2.97643402e-01,  3.48757059e-01,  3.54966556e-01,
         3.55832625e-01,  3.43754060e-01,  0.00000000e+00,
         0.00000000e+00,  9.13434170e-02,  3.46255910e-02,
         3.42821404e-02,  3.49996671e-02,  3.46522194e-02,
        -3.62324227e-03,  3.75009667e-03, -1.56142224e-01,
        -8.10235694e-02, -1.67724608e-01, -1.41790231e-01,
        -5.96028429e-02, -3.57872006e-02,  3.13619532e-02,
         3.28670518e-02,  3.40892736e-02,  3.53157440e-02,
         3.70674913e-02],
       [ 6.96582020e-03,  6.96637722e-03,  6.96737979e-03,
         6.96855603e-03,  6.96987328e-03,  2.95353039e-01,
         3.27358043e-01,  3.73073795e-01,  3.76333896e-01,
         3.63211437e-01,  7.22886346e-03,  7.22838856e-03,
         7.22784297e-03,  7.22761736e-03,  7.22779019e-03,
        -2.26695373e-01, -2.81354207e-01, -2.88067948e-01,
        -2.92193470e-01, -2.81254469e-01, -0.00000000e+00,
        -0.00000000e+00,  1.13626073e-02,  7.04204535e-03,
         6.97339474e-03,  7.24157385e-03,  7.15526966e-03,
        -1.03572213e-02,  1.85294327e-02, -6.09460473e-02,
        -3.30794194e-02, -6.50544011e-02, -5.65090431e-02,
        -2.47505714e-02, -2.19509987e-02,  5.72047626e-03,
         6.34804671e-03,  6.85946855e-03,  7.37432221e-03,
         8.11261620e-03],
       [-1.65418600e-02, -1.65419984e-02, -1.65435372e-02,
        -1.65447552e-02, -1.65453996e-02,  9.27441714e-02,
         1.08860778e-01,  1.35805430e-01,  1.39590903e-01,
         1.34596378e-01, -1.86012951e-02, -1.86011069e-02,
        -1.85999474e-02, -1.85986044e-02, -1.85975865e-02,
         5.25990477e-02,  7.62021619e-02,  8.12171499e-02,
         8.37409404e-02,  8.06873677e-02, -0.00000000e+00,
        -0.00000000e+00, -3.22608996e-03, -1.75099359e-02,
        -1.65120357e-02, -1.86268118e-02, -1.75979676e-02,
         1.13995662e-01, -1.42712451e-02,  4.62111538e-01,
         3.51263080e-01,  5.10350580e-01,  4.62533980e-01,
         1.53272158e-01,  2.01930269e-01, -7.92866285e-03,
        -1.28613177e-02, -1.68901181e-02, -2.09542510e-02,
        -2.67968552e-02],
       [-5.79910967e-03, -5.80019349e-03, -5.80194902e-03,
        -5.80251708e-03, -5.80476587e-03, -8.77955885e-03,
        -1.24081660e-02, -2.79817655e-02, -2.50385590e-02,
        -1.60327784e-02, -6.98409302e-03, -6.98302680e-03,
        -6.97967191e-03, -6.97826071e-03, -6.97721465e-03,
        -3.15971969e-03, -1.73186657e-02, -1.72803333e-02,
        -2.11197918e-02, -1.75431792e-02,  4.23516474e-22,
         1.25731453e-22,  3.05639174e-01, -7.63988666e-03,
        -5.75890126e-03, -7.02487559e-03, -5.20730473e-03,
         7.24542921e-01,  3.99615336e-01,  9.03680663e-02,
        -9.22351368e-02, -3.84244840e-02, -2.10251495e-01,
        -1.64235830e-01,  3.58628404e-01, -5.57483776e-03,
        -5.48341691e-03, -5.40734743e-03, -5.32933168e-03,
        -5.21491678e-03],
       [ 4.77792554e-03,  4.77863840e-03,  4.77934710e-03,
         4.77962374e-03,  4.77929300e-03, -1.55005035e-02,
        -7.21641825e-03,  6.76949355e-03,  1.77224986e-02,
         1.71343123e-02,  5.10606146e-03,  5.10617903e-03,
         5.10598222e-03,  5.10694050e-03,  5.10692489e-03,
         1.82681990e-02,  1.06646047e-02,  1.52587053e-02,
         1.73243540e-02,  1.48575059e-02,  4.23516474e-21,
         8.00710833e-22, -2.89628269e-01,  2.18937154e-03,
         4.78360819e-03,  5.14418407e-03,  7.50403499e-03,
        -2.34231500e-01,  8.73638589e-01,  9.14202531e-03,
         1.76009946e-01,  2.15403560e-02, -8.04619796e-02,
         1.66169460e-01, -1.72860898e-01,  2.28994715e-03,
         1.71104826e-03,  1.23743795e-03,  7.58954126e-04,
         6.98133330e-05],
       [-1.57498472e-02, -1.57514969e-02, -1.57532494e-02,
        -1.57535858e-02, -1.57548852e-02,  1.71783878e-03,
         1.10582213e-03, -2.30249892e-02, -2.47333369e-02,
        -2.00526919e-02, -1.47864364e-02, -1.47852997e-02,
        -1.47843465e-02, -1.47832380e-02, -1.47819713e-02,
         7.91662586e-03, -1.15859070e-02, -1.65119661e-02,
        -1.97183886e-02, -1.94451804e-02,  5.08219768e-21,
         1.49554255e-21,  6.04459040e-01, -1.58278558e-02,
        -1.57392505e-02, -1.47745814e-02, -1.47584526e-02,
        -5.95809411e-01,  1.75845269e-01, -4.41350363e-02,
        -6.07147455e-03,  2.20698549e-02,  6.92219219e-02,
        -1.89643366e-01,  4.45943671e-01, -1.04047809e-02,
        -1.05653926e-02, -1.06940905e-02, -1.08216487e-02,
        -1.10010200e-02],
       [-5.27161419e-03, -5.27317904e-03, -5.27338680e-03,
        -5.27460485e-03, -5.27503553e-03, -1.88940016e-02,
        -7.69154280e-03,  2.58453526e-02,  2.92795101e-02,
         2.50019362e-02, -5.21405621e-03, -5.21421849e-03,
        -5.21384131e-03, -5.21366214e-03, -5.21285067e-03,
        -9.89294184e-03,  1.26605065e-02,  1.56222077e-02,
         1.62348633e-02,  1.26504113e-02, -1.89735380e-19,
        -3.64224167e-20, -4.44002571e-01, -4.98045369e-03,
        -5.27315572e-03, -5.20721404e-03, -5.51574950e-03,
        -9.05197120e-02, -8.81079797e-02, -5.15582722e-02,
        -1.73236597e-01, -1.20404128e-01, -1.58292333e-01,
         4.30449469e-01,  7.24564213e-01, -6.74714697e-03,
        -8.49117258e-03, -9.91465948e-03, -1.13497486e-02,
        -1.34112780e-02],
       [ 5.12730806e-03,  5.12467582e-03,  5.12043061e-03,
         5.11865071e-03,  5.11594573e-03,  2.48776798e-02,
         6.46650249e-04, -2.11184060e-02, -2.67684329e-02,
        -2.11081465e-02,  5.56950381e-03,  5.57396140e-03,
         5.57738413e-03,  5.57992893e-03,  5.58253309e-03,
         5.97987166e-03, -6.37057572e-03, -1.00627373e-02,
        -1.29482282e-02, -1.21026522e-02, -1.51788304e-18,
        -2.98155597e-19, -1.31296650e-01,  5.76480032e-03,
         5.13603064e-03,  5.54737089e-03,  4.96170967e-03,
         2.02640652e-02, -1.33889406e-01, -1.42563582e-01,
         8.52483141e-01, -2.17732839e-01, -2.35414027e-01,
        -2.78355003e-01,  1.82636147e-01,  2.48531288e-03,
         6.31032434e-03,  9.43534129e-03,  1.25885834e-02,
         1.71231360e-02],
       [-2.41121402e-02, -2.41107769e-02, -2.41105142e-02,
        -2.41097570e-02, -2.41092522e-02,  3.22540061e-02,
         8.20132953e-03, -2.06832701e-02, -2.63826653e-02,
        -2.05828220e-02, -2.40473643e-02, -2.40479774e-02,
        -2.40488890e-02, -2.40497358e-02, -2.40512535e-02,
         3.38273899e-02, -1.03488281e-02, -1.65307970e-02,
        -2.38860443e-02, -2.36895498e-02, -3.25260652e-19,
        -1.21972744e-19,  4.69303976e-01, -2.38888439e-02,
        -2.41079138e-02, -2.40603534e-02, -2.42479054e-02,
         8.72819398e-02, -5.92121141e-02, -1.24667811e-01,
         2.59837616e-01, -1.18499334e-01, -1.44069289e-01,
         7.78000119e-01, -1.67840134e-01, -1.66647496e-02,
        -2.21957872e-02, -2.67114205e-02, -3.12649177e-02,
        -3.78079632e-02],
       [ 2.44193767e-03,  2.44701800e-03,  2.45675830e-03,
         2.46213679e-03,  2.46549051e-03,  8.37384267e-01,
         2.10984345e-01, -2.57768970e-01, -3.09831125e-01,
        -2.88644865e-01,  2.47616163e-03,  2.47462245e-03,
         2.47268721e-03,  2.47159249e-03,  2.46926079e-03,
        -2.17924467e-02,  7.72879096e-04,  4.30799131e-03,
        -4.19213784e-04, -8.68212943e-04, -2.42861287e-17,
        -4.66206934e-18, -6.02535362e-02,  2.43416269e-03,
         2.44251702e-03,  2.48718389e-03,  2.59221659e-03,
        -2.48657915e-03,  2.35034650e-02,  5.76395817e-04,
        -4.01803793e-02,  2.19417559e-02,  3.50828303e-02,
         6.27505723e-03,  1.93409812e-02,  1.46344079e-03,
         1.30782609e-03,  1.18030665e-03,  1.05128578e-03,
         8.65128529e-04]])